### ISSUE TITLE
Docx Templates do not seem to support Headers and Footers

### ISSUE THREAD

**Issue by GeorgeWalker** [bcgov/common-document-generation-service#90]
#### Describe the bug
We are attempting to use CDGS to render a PDF from a .DOCX template containing headers and footers. It renders the body but not the header / footer.

#### To Reproduce

Send a request to template/render with a template containing headers and footers

#### Expected behavior

The header and footer should render

#### Desktop (please complete the following information):

Tested from a C# .NET 6 application and also from the web UI.

#### Additional context
For the https://github.com/bcgov/rsbc-dmf project.

**Comment by jujaga** [comment]
There are example templates of Carbone templates with headers and footers working. Closing this issue as this is not a software issue report specifically related to the implementation of CDOGS.
